name: Daily API Request

on:
  schedule:
    # Runs every day at 3:30 PM IST (which is 10:00 AM UTC)
    - cron: "0 10 * * *"

jobs:
  hit-api:
    runs-on: ubuntu-latest

    steps:
      - name: Make API request
        run: |
          curl -X GET "https://campdash.onrender.com/update-database"
