name: Daily API Request

on:
  schedule:
    # Runs every day at 11:40 AM UTC (which is 5:10 PM IST)
    - cron: "40 11 * * *"
  workflow_dispatch:

jobs:
  hit-api:
    runs-on: ubuntu-latest

    steps:
      - name: Make API request
        run: |
          curl -X GET "https://campdash.onrender.com/update-database"
